# Assist for M5 Atom S3 Lite
# Configured as push-to-talk

esphome:
  name: assist_atoms3
  comment: AtomS3 Voice Assist
  friendly_name: Igor S3
  name_add_mac_suffix: true

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 8MB
  framework:
    type: arduino
    version: latest

logger:
api:
ota:

wifi:
  ssid: !secret ssid
  password: !secret pass

  ap:
    ssid: "Atomassist Fallback Hotspot"
    password: "SuperSecret"

captive_portal:

web_server:
  port: 80
  include_internal: true


############################ Start config under test

i2s_audio:
  # - id: i2s_in
    i2s_lrclk_pin: GPIO1
    # i2s_bclk_pin: GPIO6
  # - id: i2s_out
  #   i2s_lrclk_pin: GPIO39
  #   i2s_bclk_pin: GPIO5

microphone:
  - platform: i2s_audio
    id: ext_microphone
    # i2s_audio_id: i2s_in
    i2s_din_pin: GPIO2
    adc_type: external
    pdm: true
    on_data:
      - logger.log:
          format: "Received %d bytes"
          args: ['x.size()']

# speaker:
#   - platform: i2s_audio
#     id: echo_speaker
#     i2s_audio_id: i2s_out
#     i2s_dout_pin: GPIO38
#     dac_type: external
#     mode: mono

# Media Player on SPK Module
# media_player:
#   - platform: i2s_audio
#     icon: mdi:music-box
#     name: "Media Player"
#     id: mediaplayer
#     i2s_audio_id: i2s_out
#     i2s_dout_pin: GPIO38
#     dac_type: external
#     mode: mono
#     on_pause:
#       - script.execute: reset_led
#     on_idle:
#       - script.execute: reset_led
#     on_play:
#     - light.turn_on:
#         id: led
#         blue: 0%
#         red: 100%
#         green: 50%
#         effect: "Slow Pulse"

voice_assistant:
  microphone: ext_microphone
  # speaker: echo_speaker
  # media_player: mediaplayer
#   noise_suppression_level: 2
#   auto_gain: 31dBFS
#   volume_multiplier: 2.0
#   vad_threshold: 3
  on_listening:
    - light.turn_on:
        id: led
        blue: 100%
        red: 0%
        green: 0%
        effect: none
  on_stt_vad_end:
    - light.turn_on:
        id: led
        blue: 100%
        red: 0%
        green: 0%
        effect: "Fast Pulse"
#   on_tts_start:
#     - light.turn_on:
#         id: led
#         blue: 100%
#         red: 0%
#         green: 0%
#         brightness: 100%
#         effect: none
  on_end:
    - light.turn_on:
        id: led
        blue: 0%
        red: 0%
        green: 100%
        brightness: 100%
        effect: none
    - delay: 250ms
    # - wait_until:
    #     not:
    #       speaker.is_playing:
    - script.execute: reset_led
  on_error:
    - light.turn_on:
        id: led
        red: 100%
        green: 0%
        blue: 0%
        brightness: 100%
        effect: none
    - delay: 2s
    - script.execute: reset_led
#   on_client_connected:
#     - script.execute: reset_led
#   on_client_disconnected:
#     - voice_assistant.stop:
#     - light.turn_off: led

script:
  - id: reset_led
    then:
      - light.turn_off: led

# IR LED: G4 (uses RMT Channel 0)
# remote_transmitter:
#   pin: GPIO4
#   carrier_duty_percent: 50%

# sensor:
#   - platform: internal_temperature
#     name: "Temperature"

####################### Verified working:

# Internal RGB LED: G35
light:
  - platform: esp32_rmt_led_strip
    id: led
    name: "Internal LED"
    disabled_by_default: true
    entity_category: config
    pin: GPIO35
    default_transition_length: 0s
    chipset: ws2812
    num_leds: 1
    rgb_order: GRB
    rmt_channel: 1
    effects:
      - pulse:
          name: "Slow Pulse"
          transition_length: 500ms
          update_interval: 500ms
          min_brightness: 25%
          max_brightness: 100%
      - pulse:
          name: "Fast Pulse"
          transition_length: 50ms
          update_interval: 50ms
          min_brightness: 25%
          max_brightness: 100%

# Internal front button: G41
binary_sensor:
  - platform: gpio
    name: Module Button
    pin:
      number: GPIO41
      inverted: true
    disabled_by_default: true
    id: button
    # Push to talk config ...
    on_press:
      - voice_assistant.start:
          silence_detection: false
    on_release:
      - voice_assistant.stop:
    # ... Push to talk config
