# Assist for ESP32 NodeMCU
# Configured as push-to-talk

esphome:
  name: assist_nodemcu
  comment: NodeMCU Voice Assist
  friendly_name: Igor Node
  name_add_mac_suffix: true

esp32:
  board: nodemcu-32s
  flash_size: 4MB

logger:
api:
ota:

wifi:
  ssid: !secret ssid
  password: !secret pass

  ap:
    ssid: "Atomassist Fallback Hotspot"
    password: "SuperSecret"

captive_portal:

web_server:
  port: 80
  include_internal: true

i2s_audio:
  - id: i2s_out
    i2s_lrclk_pin: GPIO22
    i2s_bclk_pin: GPIO23


# Media Player on SPK Module
media_player:
  - platform: i2s_audio
    icon: mdi:music-box
    name: "Media Player"
    id: mediaplayer
    i2s_audio_id: i2s_out
    i2s_dout_pin: GPIO21
    dac_type: external
    mode: mono
#     on_pause:
#       - script.execute: reset_led
#     on_idle:
#       - script.execute: reset_led
#     on_play:
#     - light.turn_on:
#         id: led
#         blue: 0%
#         red: 100%
#         green: 50%
#         effect: "Slow Pulse"